### PR TITLE
updated marker type, structure, and functionality

### PR DESCRIPTION
**Pull request by Southwick-Adam**

### CODE REVIEW

**Comment by Southwick-Adam** [comment]
this should allow us to close #60 and issue #56

**Comment by Southwick-Adam** [comment]
can i assign issues to the merge? cant see the option

**Comment by Southwick-Adam** [comment]
added another commit that should close issue 35 but well have to come back to it when we get the cache running. but we can at least use this temporary solution to build the front end

**Review by smartens-bit — APPROVED** [review]
Lovely changes adam, good job!

**Pull request merged**
